import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FormProvider } from "@/contexts/FormContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "2025년 산업기술수준조사",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-auto max-w-7xl`}
      >
        <FormProvider>{children}</FormProvider>
      </body>
    </html>
  );
}
